### ISSUE TITLE
installation issue wrong scikit-learn version

### ISSUE THREAD

**Issue by hamidsta** [bm2-lab/scMVP#7]
Hello,
I'm currently trying to analyze  multiomics scRNA-ATACseq data .  However when i run this following line 
                    `> python setup.py install `
I  get this error 
                 
                    `> No local packages or working download links found for scikit-learn==0.22.2`
                    `> error: Could not find suitable distribution for Requirement.parse('scikit-learn==0.22.2') `

                     
my current version of scikit-learn : 
```
                    (base) C:\Users\User\ATAC-scMVP\scMVP>conda list scikit-learn
                    # packages in environment at C:\Users\User\anaconda3:
                    # Name                    Version                   Build  Channel
                    scikit-learn              0.24.2           py39hcf78d83_2

```
however i can't downgrade the version since  0.22.2 don't seem to be present  
              
```
    (base) C:\Users\User\ATAC-scMVP\scMVP>conda search scikit-learn
                  scikit-learn                  0.20.2  py36h343c172_0  pkgs/main
                  scikit-learn                  0.20.2  py37h343c172_0  pkgs/main
                  scikit-learn                  0.20.3  py27hf381715_0  pkgs/main
                  scikit-learn                  0.20.3  py36h343c172_0  pkgs/main
                  scikit-learn                  0.20.3  py37h343c172_0  pkgs/main
                  scikit-learn                  0.21.1  py36h6288b17_0  pkgs/main
                  scikit-learn                  0.21.1  py37h6288b17_0  pkgs/main
                  scikit-learn                  0.22.1  py38h6288b17_0  pkgs/main
                  scikit-learn                  0.23.1  py36h25d0782_0  pkgs/main
```

here is some information : 
              (base) C:\Users\User\ATAC-scMVP\scMVP>conda info
              
                   active environment : base
                  active env location : C:\Users\User\anaconda3
                          shell level : 1
                     user config file : C:\Users\User\.condarc
               populated config files : C:\Users\User\.condarc
                        conda version : 4.12.0
                  conda-build version : 3.21.6
                       python version : 3.9.7.final.0
                     virtual packages : __win=0=0
                                        __archspec=1=x86
                     base environment : C:\Users\User\anaconda3  (writable)
                    conda av data dir : C:\Users\User\anaconda3\etc\conda
                conda av metadata url : None
                         channel URLs : https://conda.anaconda.org/bioconda/win-32
                                        https://conda.anaconda.org/bioconda/noarch
                                        https://repo.anaconda.com/pkgs/main/win-32
                                        https://repo.anaconda.com/pkgs/main/noarch
                                        https://repo.anaconda.com/pkgs/r/win-32
                                        https://repo.anaconda.com/pkgs/r/noarch
                                        https://repo.anaconda.com/pkgs/msys2/win-32
                                        https://repo.anaconda.com/pkgs/msys2/noarch
                                        https://conda.anaconda.org/conda-forge/win-32
                                        https://conda.anaconda.org/conda-forge/noarch
                        package cache : C:\Users\User\anaconda3\pkgs
                                        C:\Users\User\.conda\pkgs
                                        C:\Users\User\AppData\Local\conda\conda\pkgs
                     envs directories : C:\Users\User\anaconda3\envs
                                        C:\Users\User\.conda\envs
                                        C:\Users\User\AppData\Local\conda\conda\envs
                             platform : win-32
                           user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.22000
                        administrator : False
                           netrc file : None
                         offline mode : False
              

Thanks you very much , I'm a bit lost with this issue .

**Comment by adamtongji** [comment]
It seems that the version of "scikit-learn" pip requirement may differ from version  "scikit-learn" already in your conda environment.
Can you try ``` pip install scikit-learn=0.22.2``` or install use a new conda env?

**Comment by hamidsta** [comment]
thank you ,it work now ! 
However i have a new error :/ 
here is the error 
`TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not int`

here is my session info 
          `(myenv) C:\Users\User\ATAC-scMVP\scMVP>conda info
        
           active environment : myenv
          active env location : C:\Users\User\miniconda3\envs\myenv
                  shell level : 2
             user config file : C:\Users\User\.condarc
        populated config files : C:\Users\User\.condarc
                conda version : 4.12.0
          conda-build version : not installed
               python version : 3.7.12.final.0
             virtual packages : __win=0=0
                                __archspec=1=x86_64
             base environment : C:\Users\User\miniconda3  (writable)
            conda av data dir : C:\Users\User\miniconda3\etc\conda
        conda av metadata url : None
                 channel URLs : https://conda.anaconda.org/bioconda/win-64
                                https://conda.anaconda.org/bioconda/noarch
                                https://repo.anaconda.com/pkgs/main/win-64
                                https://repo.anaconda.com/pkgs/main/noarch
                                https://repo.anaconda.com/pkgs/r/win-64
                                https://repo.anaconda.com/pkgs/r/noarch
                                https://repo.anaconda.com/pkgs/msys2/win-64
                                https://repo.anaconda.com/pkgs/msys2/noarch
                                https://conda.anaconda.org/conda-forge/win-64
                                https://conda.anaconda.org/conda-forge/noarch
                package cache : C:\Users\User\miniconda3\pkgs
                                C:\Users\User\.conda\pkgs
                                C:\Users\User\AppData\Local\conda\conda\pkgs
             envs directories : C:\Users\User\miniconda3\envs
                                C:\Users\User\.conda\envs
                                C:\Users\User\AppData\Local\conda\conda\envs
                     platform : win-64
                   user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.12 Windows/10 Windows/10.0.22000
                administrator : False
                   netrc file : None
                 offline mode : False
`
 Also  when i first run python setup.py install
2 errors messages comes up , du to module cython and NumPy not being installed. So i had to installed them directly  . Maybe the error is due to a wrong version i just download ? 
Name                    Version                   Build  Channel
cython                    0.29.28          py37hd77b12b_0
 Name                    Version                   Build  Channel
numpy                     1.21.5           py37ha4e8547_0
numpy-base                1.21.5           py37hc2deb75_0


and here is a part of the error traceback  : 

Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    zip_safe=False,
  File "C:\Users\User\miniconda3\envs\myenv\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\miniconda3\envs\myenv\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\User\miniconda3\envs\myenv\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\miniconda3\envs\myenv\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\miniconda3\envs\myenv\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\User\miniconda3\envs\myenv\lib\site-packages\setuptools\command\easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Users\User\miniconda3\envs\myenv\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\User\miniconda3\envs\myenv\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\User\miniconda3\envs\myenv\lib\multiprocessing\popen_spawn_win32.py", line 67, in __init__
    with open(wfd, 'wb', closefd=True) as to_child:
  File "C:\Users\User\miniconda3\envs\myenv\lib\site-packages\setuptools\sandbox.py", line 453, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
  File "C:\Users\User\miniconda3\envs\myenv\lib\site-packages\setuptools\sandbox.py", line 464, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
  File "C:\Users\User\miniconda3\envs\myenv\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
**TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not int**
